print(4 < 8)
print(4 > 8)
print(4 == 8)
print(4 <= 8)
print(4 >= 8)
print(4 != 8)
print('hola' > 'mundo')
print('hola' > 'bolas')
print('hola' == 'hola')  
print('a' < 'b')
print('aaa' > 'aba')
print('c' == 'b')
print('martin' > 'betty')
print('martin' < 'betty')

